### PR TITLE
Fix presser audit typos

### PR DESCRIPTION
**Pull request by fu5ha**
Fixes https://github.com/EmbarkStudios/rust-ecosystem/pull/91/files#r1038109294

### CODE REVIEW

**Review by repi — APPROVED** [review]

**Comment by repi** [comment]
oh @fu5ha you didn't remove the wrong `puffin` audit in here!

**Comment by repi** [comment]
third time the charm?

**Comment by fu5ha** [comment]
Oops hahaha. I guess because I fixed it on my exisitng branch rather than making a new patch on main. Thanks!

**Comment by repi** [comment]
ah that's why I missed it also because I searched through the file in your PR, but didn't spot it

**Pull request merged**
