### PR TITLE
Embark standard lints v0.4 - require Rust 1.52

### PR DESCRIPTION
**Pull request by repi**
With these changes our standard lint set now requires Rust 1.52, and builds on Rust 1.53 / beta / nightly without warnings about renamed/changed lints.

## Removals

- [`clippy::pub_enum_variant_names`](https://rust-lang.github.io/rust-clippy/master/#pub_enum_variant_names) - This was removed in Rust 1.53 so can't be in our standard lint set anymore.
- [`clippy::suboptimal_flops`](https://rust-lang.github.io/rust-clippy/master/#suboptimal_flops) - Harder to read and perf degradations, see discussions in #63 and https://github.com/rust-lang/rust-clippy/issues/6867

## Additions

Enables the following lints that we've been testing with in Ark for a few months. Many of them are somewhat low impact but low cost so just nice to have enabled.

- [`clippy::char_lit_as_u8`](https://rust-lang.github.io/rust-clippy/master/#char_lit_as_u8)
- [`clippy::checked_conversions`](https://rust-lang.github.io/rust-clippy/master/#checked_conversions)
- [`clippy::expl_impl_clone_on_copy`](https://rust-lang.github.io/rust-clippy/master/#expl_impl_clone_on_copy)
- [`clippy::explicit_deref_methods`](https://rust-lang.github.io/rust-clippy/master/#explicit_deref_methods)
- [`clippy::fallible_impl_from`](https://rust-lang.github.io/rust-clippy/master/#fallible_impl_from)
- [`clippy::float_cmp_const`](https://rust-lang.github.io/rust-clippy/master/#float_cmp_const)
- [`clippy::implicit_clone`](https://rust-lang.github.io/rust-clippy/master/#implicit_clone) - More explicit have have also found redundant clones with it which is nice
- [`clippy::invalid_upcast_comparisons`](https://rust-lang.github.io/rust-clippy/master/#invalid_upcast_comparisons)
- [`clippy::manual_ok_or`](https://rust-lang.github.io/rust-clippy/master/#manual_ok_or)
- [`clippy::mut_mut`](https://rust-lang.github.io/rust-clippy/master/#mut_mut)
- [`clippy::mutex_integer`](https://rust-lang.github.io/rust-clippy/master/#mutex_integer)
- [`clippy::path_buf_push_overwrite`](https://rust-lang.github.io/rust-clippy/master/#path_buf_push_overwrite)
- [`clippy::ptr_as_ptr`](https://rust-lang.github.io/rust-clippy/master/#ptr_as_ptr)
- [`clippy::same_functions_in_if_condition`](https://rust-lang.github.io/rust-clippy/master/#same_functions_in_if_condition)
- [`clippy::semicolon_if_nothing_returned`](https://rust-lang.github.io/rust-clippy/master/#semicolon_if_nothing_returned) - This one is really quite pedantic and typically a bunch of small fixups. But is easy to do and keeps it explicit
- [`clippy::string_lit_as_bytes`](https://rust-lang.github.io/rust-clippy/master/#string_lit_as_bytes)
- [`clippy::trait_duplication_in_bounds`](https://rust-lang.github.io/rust-clippy/master/#trait_duplication_in_bounds)
- [`clippy::useless_transmute`](https://rust-lang.github.io/rust-clippy/master/#useless_transmute)
- [`clippy::zero_sized_map_values`](https://rust-lang.github.io/rust-clippy/master/#zero_sized_map_values)

Part of #59

### CODE REVIEW

**Comment by repi** [comment]
@khyperia can you test using this draft set in rust-gpu and see if there are any new lints that are problematic in it? If it is serious we could exclude it from here, or otherwise just override in that repro itself. 

These do work fine in ark and our modules.

**Review by Jake-Shadle — APPROVED** [review]
LGTM!

**Comment by repi** [comment]
@khyperia thanks for testing! oops had forgotten to push the latest that fixed the ending and included two new lints (`implicit_clone` and `semicolon_if_nothing_returned`). 

Think we can get this in today then.  I did take a look at the new clippy lints in Rust 1.53 but of the 4 new none of them were that interesting for now, so think fine to settle on 1.52 as requirement for this

**Review by khyperia — APPROVED** [review]

**Comment by MarijnS95** [comment]
> * [`clippy::semicolon_if_nothing_returned`](https://rust-lang.github.io/rust-clippy/master/#semicolon_if_nothing_returned) - This one is really quite pedantic and typically a bunch of small fixups. But is easy to do and keeps it explicit

Interesting choice! I've been advocating this the other way around to guarantee (by the compiler) that the return types (usually void, `()`) match up. If the inner function suddenly changes return signature but lacks a `#[must_use]` this is now easily caught instead of going unnoticed.

Other than that another nice set of lints! `ptr_as_ptr` is quite some churn for us but was planned anyway and it's great to have it enabled now!

**Pull request merged**
